version: '3.7'

services:
    backend:
        build: 
            context: .
            dockerfile: Dockerfile.backend
        depends_on:
            - db
        volumes:
            - ./backend/data:/app
        environment:
            DATABASE_URL: "postgres://postgres@db/postgres"
            FLASK_APP: "run.py"
            FLASK_ENV: development
        ports:
            - "7070:5000"
    db:
        image: postgres
        restart: always
        volumes:  
            - dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
    pgadmin:
        build: 
            context: .
            dockerfile: Dockerfile.pgadmin
        volumes: 
            - pgdata:/var/lib/pgadmin/data
        ports: 
            - "9090:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
    dbdata:
        driver: local

    pgdata:
        driver: local

networks:
    test-network:
        driver: bridge